title:              Aziz Faozi
email:              faoziaziz@s.itb.ac.id
description:        Tet teret tet
author:             Start Bootstrap
baseurl:            "/"
url:                "https://faoziaziz.github.io"

# Social Profiles
twitter_username:   AzizFaozi4
github_username:    faoziaziz
facebook_username:  phonospher
instagram_username:  faozi.aziz
linkedin_username: aziz-faozi-169102244

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
